/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica5joaquinzavala.vista.Cancion;

import ec.edu.ups.practica5joaquinzavala.controlador.ControladorCompositor;
import ec.edu.ups.practica5joaquinzavala.modelo.Cancion;
import ec.edu.ups.practica5joaquinzavala.modelo.Compositor;
import javax.swing.JOptionPane;

/**
 *
 * @author ESTUDIANTE
 */
public class VentanaEliminarCancion extends javax.swing.JInternalFrame {

    private ControladorCompositor controladorCompositor;
    private Compositor compositor;
    public VentanaEliminarCancion(ControladorCompositor controladorCompositor) {
        initComponents();
        this.controladorCompositor = controladorCompositor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnBuscarCompositor = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelTiempoEnMinutos = new javax.swing.JLabel();
        jLabelTituloCancion = new javax.swing.JLabel();
        jLabelCodigoCancion = new javax.swing.JLabel();
        txtCodigoCancion = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtTiempoEnMinutos = new javax.swing.JTextField();
        btnDeleteCancion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabelLetra1 = new javax.swing.JLabel();
        txtLetra = new javax.swing.JTextField();
        btnBuscarCancion = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Eliminar Cancion");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Eliminar una cancion");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 191, -1));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 36, -1, 190));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disco.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 190));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compositorImagen.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 190));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setEnabled(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(204, 204, 255));
        jLabel12.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jLabel12.setText("Apellido");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 227, 114, 45));

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jLabel13.setText("Nombre");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 176, 114, 45));

        jLabel14.setBackground(new java.awt.Color(204, 204, 255));
        jLabel14.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jLabel14.setText("Codigo");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 125, 114, 45));

        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel6.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 138, 295, -1));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setEnabled(false);
        jPanel6.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 189, 295, -1));

        txtApellido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtApellido.setEnabled(false);
        jPanel6.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 240, 295, -1));

        btnBuscarCompositor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btnBuscarCompositor.setText("Buscar");
        btnBuscarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCompositorActionPerformed(evt);
            }
        });
        jPanel6.add(btnBuscarCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jLabel15.setText("Buscar un compositor");
        jLabel15.setToolTipText("");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 465, -1));

        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setEnabled(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTiempoEnMinutos.setBackground(new java.awt.Color(204, 204, 255));
        jLabelTiempoEnMinutos.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jLabelTiempoEnMinutos.setText("TiempoEnMinutos");
        jPanel5.add(jLabelTiempoEnMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 200, 45));

        jLabelTituloCancion.setBackground(new java.awt.Color(204, 204, 255));
        jLabelTituloCancion.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jLabelTituloCancion.setText("Titulo");
        jPanel5.add(jLabelTituloCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 114, 45));

        jLabelCodigoCancion.setBackground(new java.awt.Color(204, 204, 255));
        jLabelCodigoCancion.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jLabelCodigoCancion.setText("Codigo");
        jPanel5.add(jLabelCodigoCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 114, 45));

        txtCodigoCancion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodigoCancion.setEnabled(false);
        jPanel5.add(txtCodigoCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 295, -1));

        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTitulo.setEnabled(false);
        jPanel5.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 295, -1));

        txtTiempoEnMinutos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTiempoEnMinutos.setEnabled(false);
        jPanel5.add(txtTiempoEnMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 295, -1));

        btnDeleteCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/deleteCD.png"))); // NOI18N
        btnDeleteCancion.setText("Eliminar");
        btnDeleteCancion.setEnabled(false);
        btnDeleteCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCancionActionPerformed(evt);
            }
        });
        jPanel5.add(btnDeleteCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/deleteE.png"))); // NOI18N
        jLabel1.setText("ActualizarDisco");
        jLabel1.setToolTipText("");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 465, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel5.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        jLabelLetra1.setBackground(new java.awt.Color(204, 204, 255));
        jLabelLetra1.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jLabelLetra1.setText("Letra");
        jPanel5.add(jLabelLetra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 114, 45));

        txtLetra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLetra.setEnabled(false);
        jPanel5.add(txtLetra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 295, -1));

        btnBuscarCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btnBuscarCancion.setEnabled(false);
        btnBuscarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCancionActionPerformed(evt);
            }
        });
        jPanel5.add(btnBuscarCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCompositorActionPerformed
        int codigo = Integer.parseInt(txtCodigo.getText());
        this.compositor = controladorCompositor.buscarCompositor(codigo);
        if (compositor != null) {
            txtApellido.setText(compositor.getApellido());
            txtNombre.setText(compositor.getNombre());
            cambiarEstado(true);
        }else{
            JOptionPane.showMessageDialog(this, "No se encontrado compositor");
        }
    }//GEN-LAST:event_btnBuscarCompositorActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        cambiarEstado(false);
        cambiarEstadoDatosCancion(false);
        limipiarCampos();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnDeleteCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCancionActionPerformed
        int codigo = Integer.parseInt(txtCodigo.getText());
        int codigoCancion = Integer.parseInt(txtCodigoCancion.getText());
        this.compositor = controladorCompositor.buscarCompositor(codigo);
        Cancion cancion = controladorCompositor.buscarCancion(compositor, codigoCancion);
        
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Quieres elimar de la lista a: " + cancion.getTitulo()+ " ?");
        if (respuesta == JOptionPane.YES_OPTION) {
            controladorCompositor.eliminarCancion(compositor, codigoCancion);
            JOptionPane.showMessageDialog(this, "La cancion se a eliminado");
            this.limipiarCampos();
            this.limipiarCamposCancion();
            this.cambiarEstadoDatosCancion(true);
            this.cambiarEstado(false);
            
        } else {
            JOptionPane.showMessageDialog(this, "La cancion no ha sido eliminado");
            this.limipiarCampos();
            this.limipiarCamposCancion();
            this.cambiarEstadoDatosCancion(true);
            this.cambiarEstado(false);
        }
    }//GEN-LAST:event_btnDeleteCancionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        this.limipiarCampos();
        this.limipiarCamposCancion();
        this.cambiarEstado(false);
        this.cambiarEstadoDatosCancion(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCancionActionPerformed
        int codigo = Integer.parseInt(txtCodigo.getText());
        this.compositor = controladorCompositor.buscarCompositor(codigo);
        int codigoCancion = Integer.parseInt(txtCodigoCancion.getText());
        Cancion cancion = controladorCompositor.buscarCancion(compositor, codigoCancion);
        if (cancion != null) {
            txtTiempoEnMinutos.setText(String.valueOf(cancion.getTiempoEnMinutos()));
            txtTitulo.setText(cancion.getTitulo());
            txtLetra.setText(cancion.getLetra());
            cambiarEstadoDatosCancion(true);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontrado la cancion");
            this.limipiarCamposCancion();
        }
    }//GEN-LAST:event_btnBuscarCancionActionPerformed

     private void cambiarEstado(boolean bandera){
        txtCodigo.setEnabled(!bandera);
        txtCodigoCancion.setEnabled(bandera);
        btnBuscarCancion.setEnabled(bandera);
    }
    private void cambiarEstadoDatosCancion(boolean bandera){
        btnDeleteCancion.setEnabled(bandera);
        txtCodigo.setEnabled(!bandera);
        txtCodigoCancion.setEnabled(!bandera);
    }
    private void limipiarCamposCancion(){
        txtCodigoCancion.setText("");
        txtLetra.setText("");
        txtTiempoEnMinutos.setText("");
        txtTitulo.setText("");
    }
    private void limipiarCampos(){
        txtCodigo.setText("");
        txtApellido.setText("");
        txtNombre.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCancion;
    private javax.swing.JButton btnBuscarCompositor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnDeleteCancion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCodigoCancion;
    private javax.swing.JLabel jLabelLetra1;
    private javax.swing.JLabel jLabelTiempoEnMinutos;
    private javax.swing.JLabel jLabelTituloCancion;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCancion;
    private javax.swing.JTextField txtLetra;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTiempoEnMinutos;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
