/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica5joaquinzavala.vista.cliente;

import ec.edu.ups.practica5joaquinzavala.controlador.ControladorCompositor;
import ec.edu.ups.practica5joaquinzavala.modelo.Cantante;
import ec.edu.ups.practica5joaquinzavala.modelo.Compositor;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;



public class VentanaEliminarCliente extends javax.swing.JInternalFrame {
    private Compositor  compositor;
    private Cantante cantante;
    private ControladorCompositor controladorCompositor;
    private ResourceBundle mensajes;
    
    
    public void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jblApe.setText(mensajes.getString("jlb.ape"));
        jblApe2.setText(mensajes.getString("jlb.ape"));
        jblCod.setText(mensajes.getString("jlb.cod"));
        jblCod2.setText(mensajes.getString("jlb.cod"));
        jblCon.setText(mensajes.getString("jlb.con"));
        jblEda.setText(mensajes.getString("jlb.eda"));
        jblGenMus.setText(mensajes.getString("jlb.genmus"));
        jblMenPanCl.setText(mensajes.getString("jlb.ingnue"));
        jblMenPanC.setText(mensajes.getString("menuitem.buscom"));
        jblNac.setText(mensajes.getString("jlb.nac"));
        jblNom.setText(mensajes.getString("jlb.nom"));
        jblNom2.setText(mensajes.getString("jlb.nom"));
        jblNomArt.setText(mensajes.getString("jlb.nomart"));
        jblSal.setText(mensajes.getString("jlb.sal"));
        btnBuscarCompositor.setText(mensajes.getString("btn.bus"));
        btnCancelar.setText(mensajes.getString("btn.can"));
        btnCancelarTotal.setText(mensajes.getString("btn.can"));
        jblTit.setText(mensajes.getString("menuitem.elicli"));
        btnEliminar.setText(mensajes.getString("btn.eli"));
        
        this.setTitle(mensajes.getString("menuitem.elicli"));
        
        
    }
    
    public VentanaEliminarCliente(ControladorCompositor controladorCompositor) {
        initComponents();
        this.controladorCompositor = controladorCompositor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jblCod2 = new javax.swing.JLabel();
        txtCodigoCantante = new javax.swing.JTextField();
        btnBuscarCantante = new javax.swing.JButton();
        jblMenPanCl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jblTit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jblCod = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jblNom = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jblApe = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jblMenPanC = new javax.swing.JLabel();
        btnBuscarCompositor = new javax.swing.JButton();
        btnCancelarTotal = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jblApe2 = new javax.swing.JLabel();
        jblNom2 = new javax.swing.JLabel();
        jblNac = new javax.swing.JLabel();
        jblSal = new javax.swing.JLabel();
        jblEda = new javax.swing.JLabel();
        jblSen = new javax.swing.JLabel();
        jblGenMus = new javax.swing.JLabel();
        jblNomArt = new javax.swing.JLabel();
        jblGir = new javax.swing.JLabel();
        jblCon = new javax.swing.JLabel();
        txtNombreCantante = new javax.swing.JTextField();
        txtApellidoCantante = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        txtNombreArtistico = new javax.swing.JTextField();
        txtSencillos = new javax.swing.JTextField();
        txtGiras = new javax.swing.JTextField();
        txtConciertos = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        txtNacionalidad = new javax.swing.JTextField();
        txtGeneroMuscical = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar Cliente"));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel5.setBackground(java.awt.Color.lightGray);
        jPanel5.setForeground(new java.awt.Color(60, 63, 65));
        jPanel5.setToolTipText("");
        jPanel5.setAutoscrolls(true);
        jPanel5.setEnabled(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblCod2.setBackground(new java.awt.Color(204, 204, 255));
        jblCod2.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblCod2.setText("Codigo");
        jPanel5.add(jblCod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 114, 45));

        txtCodigoCantante.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodigoCantante.setEnabled(false);
        jPanel5.add(txtCodigoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 295, -1));

        btnBuscarCantante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btnBuscarCantante.setEnabled(false);
        btnBuscarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCantanteActionPerformed(evt);
            }
        });
        jPanel5.add(btnBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jblMenPanCl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jblMenPanCl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jblMenPanCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cantante jlabel.png"))); // NOI18N
        jblMenPanCl.setText("   Buscar un cantante");
        jblMenPanCl.setToolTipText("");
        jPanel5.add(jblMenPanCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 480, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblTit.setText("Eliminar Cliente");
        jPanel2.add(jblTit, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 191, -1));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 36, -1, 190));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cantante.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, 190));

        jblCod.setBackground(new java.awt.Color(204, 204, 255));
        jblCod.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblCod.setText("Codigo");
        jPanel2.add(jblCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 114, 45));

        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 295, -1));

        jblNom.setBackground(new java.awt.Color(204, 204, 255));
        jblNom.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblNom.setText("Nombre");
        jPanel2.add(jblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 114, 45));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 295, -1));

        jblApe.setBackground(new java.awt.Color(204, 204, 255));
        jblApe.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblApe.setText("Apellido");
        jPanel2.add(jblApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 114, 45));

        txtApellido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtApellido.setEnabled(false);
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 295, -1));

        jblMenPanC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jblMenPanC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jblMenPanC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busquedaCliente.png"))); // NOI18N
        jblMenPanC.setText("  Buscar Compositor");
        jblMenPanC.setToolTipText("");
        jPanel2.add(jblMenPanC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 330, -1));

        btnBuscarCompositor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btnBuscarCompositor.setText("Buscar");
        btnBuscarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCompositorActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        btnCancelarTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnCancelarTotal.setText("Cancelar");
        btnCancelarTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTotalActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelarTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, -1, -1));

        jPanel6.setBackground(new java.awt.Color(102, 153, 255));

        jblApe2.setBackground(new java.awt.Color(204, 204, 255));
        jblApe2.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblApe2.setText("Apellido");

        jblNom2.setBackground(new java.awt.Color(204, 204, 255));
        jblNom2.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblNom2.setText("Nombre");

        jblNac.setBackground(new java.awt.Color(204, 204, 255));
        jblNac.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblNac.setText("Nacionalidad");

        jblSal.setBackground(new java.awt.Color(204, 204, 255));
        jblSal.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblSal.setText("Salario");

        jblEda.setBackground(new java.awt.Color(204, 204, 255));
        jblEda.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblEda.setText("Edad");

        jblSen.setBackground(new java.awt.Color(204, 204, 255));
        jblSen.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblSen.setText("Sencillos");

        jblGenMus.setBackground(new java.awt.Color(204, 204, 255));
        jblGenMus.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblGenMus.setText("GeneroMusical");

        jblNomArt.setBackground(new java.awt.Color(204, 204, 255));
        jblNomArt.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblNomArt.setText("NombreArtistico");

        jblGir.setBackground(new java.awt.Color(204, 204, 255));
        jblGir.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblGir.setText("Giras");

        jblCon.setBackground(new java.awt.Color(204, 204, 255));
        jblCon.setFont(new java.awt.Font("Roman", 0, 18)); // NOI18N
        jblCon.setText("Conciertos");

        txtNombreCantante.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombreCantante.setToolTipText("Introduce tu Nombre");
        txtNombreCantante.setEnabled(false);

        txtApellidoCantante.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtApellidoCantante.setToolTipText("Introduce tu Apellido");
        txtApellidoCantante.setEnabled(false);

        txtEdad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEdad.setToolTipText("Introduce tu Edad");
        txtEdad.setEnabled(false);

        txtSalario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSalario.setToolTipText("Introduce tu Salario");
        txtSalario.setEnabled(false);

        txtNombreArtistico.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombreArtistico.setToolTipText("Introduce tu Nombre Artistico");
        txtNombreArtistico.setEnabled(false);

        txtSencillos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSencillos.setToolTipText("Introduce tu cantidad de sencillos");
        txtSencillos.setEnabled(false);

        txtGiras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGiras.setToolTipText("Introduce tu cantidad de giras");
        txtGiras.setEnabled(false);
        txtGiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGirasActionPerformed(evt);
            }
        });

        txtConciertos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtConciertos.setToolTipText("Introduce tu cantidad de conciertos");
        txtConciertos.setEnabled(false);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtNacionalidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNacionalidad.setToolTipText("Introduce tu cantidad de giras");
        txtNacionalidad.setEnabled(false);
        txtNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacionalidadActionPerformed(evt);
            }
        });

        txtGeneroMuscical.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGeneroMuscical.setToolTipText("Introduce tu cantidad de sencillos");
        txtGeneroMuscical.setEnabled(false);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_cancel.png"))); // NOI18N
        btnEliminar.setText("Elminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblGir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jblApe2)
                                    .addComponent(jblSen)
                                    .addComponent(jblSal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiras, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSencillos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidoCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jblNom2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jblNomArt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jblGenMus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jblCon, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jblEda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtConciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGeneroMuscical, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jblNac, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(77, 77, 77)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblNom2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCantante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNomArt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblApe2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoCantante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblEda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jblSal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jblCon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtConciertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblGenMus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeneroMuscical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSencillos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblSen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblGir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNac, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminar))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void limipiarCamposCantante(){
        txtCodigoCantante.setText("");
        txtNombreCantante.setText("");
        txtApellidoCantante.setText("");
        txtNombreArtistico.setText("");
        txtEdad.setText("");
        txtSencillos.setText("");
        txtGeneroMuscical.setText("");
        txtSalario.setText("");
        txtGiras.setText("");
        txtConciertos.setText("");
        txtNacionalidad.setText("");
    }
    private void limipiarCampos(){
        txtNombre.setText("");
        txtApellido.setText("");
        txtCodigo.setText("");
    }
    
    private void cambiarEstado(boolean bandera){
        btnBuscarCompositor.setEnabled(!bandera);
        txtCodigo.setEnabled(!bandera);
        btnBuscarCantante.setEnabled(bandera);
        txtCodigoCantante.setEnabled(bandera);
        btnEliminar.setEnabled(bandera);
    }
    
    
    private void btnBuscarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCompositorActionPerformed
        
        int codigo = Integer.parseInt(txtCodigo.getText());
        this.compositor = controladorCompositor.buscarCompositor(codigo);
        if (compositor != null) {
            txtApellido.setText(compositor.getApellido());
            txtNombre.setText(compositor.getNombre());
            cambiarEstado(true);
        }else{
            JOptionPane.showMessageDialog(this, "El compositor aun no ha sido registrado");
        }
    }//GEN-LAST:event_btnBuscarCompositorActionPerformed

    private void btnCancelarTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTotalActionPerformed
        this.setVisible(false);
        cambiarEstado(false);
        limipiarCampos();
        limipiarCamposCantante();
    }//GEN-LAST:event_btnCancelarTotalActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.setVisible(false);
        this.limipiarCampos();
        this.limipiarCamposCantante();
        this.cambiarEstado(false);
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
          // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnBuscarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCantanteActionPerformed
        int codigoCantane = Integer.parseInt(txtCodigoCantante.getText());
        int codigoCompositor = Integer.parseInt(txtCodigo.getText());
        
        this.compositor = controladorCompositor.buscarCompositor(codigoCompositor);
        
        this.cantante = controladorCompositor.buscarCliente(compositor, codigoCantane);
        
        if (cantante != null) {
            txtApellidoCantante.setText(cantante.getApellido());
            txtEdad.setText(String.valueOf(cantante.getEdad()));
            txtGeneroMuscical.setText(cantante.getGeneroMusical().toString());
            txtNacionalidad.setText(cantante.getNacionalidad().toString());
            txtNombreCantante.setText(cantante.getNombre());
            txtNombreArtistico.setText(cantante.getNombreArtistico());
            txtConciertos.setText(String.valueOf(cantante.getNumeroDeConciertos()));
            txtGiras.setText(String.valueOf(cantante.getNumeroDeGiras()));

            txtSencillos.setText(String.valueOf(String.valueOf(cantante.getNumeroDeSensillos())));
            txtSalario.setText(String.valueOf(String.valueOf(cantante.calularSalario())));
            
        } else {
            JOptionPane.showMessageDialog(this, "El cantante con el codigo " + codigoCantane + " no ha sido registrado");
            limipiarCamposCantante();
        }
    }//GEN-LAST:event_btnBuscarCantanteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.cambiarEstado(false);
        this.limipiarCamposCantante();
        this.limipiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtGirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGirasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGirasActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int codigo = Integer.parseInt(txtCodigo.getText());
        this.compositor = controladorCompositor.buscarCompositor(codigo);
        if (!txtCodigoCantante.getText().isEmpty()) {
            int codigoCantante = Integer.parseInt(txtCodigoCantante.getText());
            this.cantante = controladorCompositor.buscarCliente(compositor, codigoCantante);
        }
        if(cantante == null || compositor == null){
            JOptionPane.showMessageDialog(this, "No se a encontrado el cliente");
            return;
        }
        
        
        
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Quieres elimar de la lista a: " + cantante.getNombre()+"?");
        if (respuesta == JOptionPane.YES_OPTION) {
            controladorCompositor.eliminarCliente(compositor, cantante);
            JOptionPane.showMessageDialog(this, "El cliente ha sido eliminado");
            
        } else {
            JOptionPane.showMessageDialog(this, "El compositor no ha sido eliminado");
        }
        this.limipiarCampos();
        this.limipiarCamposCantante();
        this.cambiarEstado(false);
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCantante;
    private javax.swing.JButton btnBuscarCompositor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarTotal;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jblApe;
    private javax.swing.JLabel jblApe2;
    private javax.swing.JLabel jblCod;
    private javax.swing.JLabel jblCod2;
    private javax.swing.JLabel jblCon;
    private javax.swing.JLabel jblEda;
    private javax.swing.JLabel jblGenMus;
    private javax.swing.JLabel jblGir;
    private javax.swing.JLabel jblMenPanC;
    private javax.swing.JLabel jblMenPanCl;
    private javax.swing.JLabel jblNac;
    private javax.swing.JLabel jblNom;
    private javax.swing.JLabel jblNom2;
    private javax.swing.JLabel jblNomArt;
    private javax.swing.JLabel jblSal;
    private javax.swing.JLabel jblSen;
    private javax.swing.JLabel jblTit;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoCantante;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCantante;
    private javax.swing.JTextField txtConciertos;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGeneroMuscical;
    private javax.swing.JTextField txtGiras;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreArtistico;
    private javax.swing.JTextField txtNombreCantante;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtSencillos;
    // End of variables declaration//GEN-END:variables

}
