/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.practica5joaquinzavala.vista;

import ec.edu.ups.practica5joaquinzavala.controlador.ControladorCantante;
import ec.edu.ups.practica5joaquinzavala.controlador.ControladorCompositor;
import ec.edu.ups.practica5joaquinzavala.dao.CantanteDAO;
import ec.edu.ups.practica5joaquinzavala.dao.CompositorDAO;
import ec.edu.ups.practica5joaquinzavala.vista.Cancion.VentanaActualizarCancion;
import ec.edu.ups.practica5joaquinzavala.vista.Cancion.VentanaBuscarCancion;
import ec.edu.ups.practica5joaquinzavala.vista.Cancion.VentanaCrearCancion;
import ec.edu.ups.practica5joaquinzavala.vista.Cancion.VentanaEliminarCancion;
import ec.edu.ups.practica5joaquinzavala.vista.Cancion.VentanaListarCancion;
import ec.edu.ups.practica5joaquinzavala.vista.Cantante.VentanaActualizarCantante;
import ec.edu.ups.practica5joaquinzavala.vista.Cantante.VentanaBuscarCantante;
import ec.edu.ups.practica5joaquinzavala.vista.Cantante.VentanaCrearCantante;
import ec.edu.ups.practica5joaquinzavala.vista.Cantante.VentanaEliminarCantante;
import ec.edu.ups.practica5joaquinzavala.vista.Cantante.VentanaListarCantante;
import ec.edu.ups.practica5joaquinzavala.vista.Compositor.VentanaActualizarCompositor;
import ec.edu.ups.practica5joaquinzavala.vista.Compositor.VentanaBuscarCompositor;
import ec.edu.ups.practica5joaquinzavala.vista.Compositor.VentanaCrearCompositor;
import ec.edu.ups.practica5joaquinzavala.vista.Compositor.VentanaEliminarCompositor;
import ec.edu.ups.practica5joaquinzavala.vista.Compositor.VentanaListarCompositor;
import ec.edu.ups.practica5joaquinzavala.vista.cliente.VentanaActualizarCliente;
import ec.edu.ups.practica5joaquinzavala.vista.cliente.VentanaBuscarCliente;
import ec.edu.ups.practica5joaquinzavala.vista.cliente.VentanaCrearCliente;
import ec.edu.ups.practica5joaquinzavala.vista.disco.VentanaActualizarDisco;
import ec.edu.ups.practica5joaquinzavala.vista.disco.VentanaBuscarDisco;
import ec.edu.ups.practica5joaquinzavala.vista.disco.VentanaCrearDisco;
import ec.edu.ups.practica5joaquinzavala.vista.disco.VentanaEliminarDisco;
import ec.edu.ups.practica5joaquinzavala.vista.disco.VentanaListarDisco;



/**
 *
 * @author SOPORTETICS
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaCrearCantante ventanaCrearCantante;
    private VentanaBuscarCantante ventanaBuscarCantante;
    private VentanaActualizarCantante ventanaActualizarCantante;
    private VentanaEliminarCantante ventanaEliminarCantante;
    private VentanaListarCantante ventanaListarCantante;
    
    private VentanaCrearDisco ventanaCrearDisco;
    private VentanaBuscarDisco ventanaBuscarDisco;
    private VentanaActualizarDisco ventanaActualizarDisco;
    private VentanaEliminarDisco ventanaEliminarDisco;
    private VentanaListarDisco ventanaListarDisco;
    
    private VentanaCrearCompositor ventanaCrearCompositor;
    private VentanaBuscarCompositor ventanaBuscarCompositor;
    private VentanaActualizarCompositor ventanaActualizarCompositor;
    private VentanaEliminarCompositor ventanaEliminarCompositor;
    private VentanaListarCompositor ventanaListarCompositor;

    private VentanaCrearCancion ventanaCrearCancion;
    private VentanaBuscarCancion ventanaBuscarCancion;
    private VentanaActualizarCancion ventanaActualizarCancion;
    private VentanaEliminarCancion ventanaEliminarCancion;
    private VentanaListarCancion ventanaListarCancion;
    
    private VentanaCrearCliente ventanaCrearCliente;
    private VentanaBuscarCliente ventanaBuscarCliente;
    private VentanaActualizarCliente ventanaActualizarCliente;

    private ControladorCantante controladorCantante;
    private ControladorCompositor controladorCompositor;

    private CantanteDAO cantanteDAO;
    private CompositorDAO compositorDAO;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        cantanteDAO = new CantanteDAO();
        controladorCantante = new ControladorCantante(cantanteDAO);
        compositorDAO = new CompositorDAO();
        controladorCompositor = new ControladorCompositor(compositorDAO, cantanteDAO);

    }

    //System.exit(0);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        itemMenuCrearCantante = new javax.swing.JMenuItem();
        itemMenuVerCantante = new javax.swing.JMenuItem();
        menuItemActualizarCantante = new javax.swing.JMenuItem();
        menuItemListarCantante = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemMenuRegistrarDisco = new javax.swing.JMenuItem();
        menuItemBuscarDisco = new javax.swing.JMenuItem();
        menuItemActualizarDisco = new javax.swing.JMenuItem();
        menuItemEliminarDisco = new javax.swing.JMenuItem();
        menuItemListarDisco = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemMenuRegistrarDisco2 = new javax.swing.JMenuItem();
        menuItemBuscarDisco2 = new javax.swing.JMenuItem();
        menuItemActualizarDisco2 = new javax.swing.JMenuItem();
        menuItemEliminarDisco2 = new javax.swing.JMenuItem();
        menuItemListarDisco2 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        menuItemRegistrarCompositor = new javax.swing.JMenuItem();
        menuItemBuscarCompositor = new javax.swing.JMenuItem();
        menuItemActualizarCompositor = new javax.swing.JMenuItem();
        menuItemEliminarCompositor = new javax.swing.JMenuItem();
        menuItemListarCompositor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemRegistrarCancion = new javax.swing.JMenuItem();
        menuItemBuscarCancion = new javax.swing.JMenuItem();
        menuItemActualizarCancion = new javax.swing.JMenuItem();
        menuItemEliminarCancion = new javax.swing.JMenuItem();
        menuItemListarCancion = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuItemRegistrarCliente = new javax.swing.JMenuItem();
        menuItemBuscarCliente = new javax.swing.JMenuItem();
        menuItemActulalizarCliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemRegistrarCancion1 = new javax.swing.JMenuItem();
        menuItemBuscarCancion1 = new javax.swing.JMenuItem();
        menuItemActualizarCancion1 = new javax.swing.JMenuItem();
        menuItemEliminarCancion1 = new javax.swing.JMenuItem();
        menuItemListarCancion1 = new javax.swing.JMenuItem();
        menuItemRegistrarCliente1 = new javax.swing.JMenu();
        menuItemRegistrarCliente2 = new javax.swing.JMenuItem();
        menuItemBuscarCliente2 = new javax.swing.JMenuItem();
        menuItemActulalizarCliente1 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi Aplicaion");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        desktopPane.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        menuBar.setMinimumSize(new java.awt.Dimension(400, 32000));

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuDos-menu.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Cantante");

        itemMenuCrearCantante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-usuario-menu.png"))); // NOI18N
        itemMenuCrearCantante.setMnemonic('o');
        itemMenuCrearCantante.setText("Registrar cantante");
        itemMenuCrearCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCrearCantanteActionPerformed(evt);
            }
        });
        fileMenu.add(itemMenuCrearCantante);

        itemMenuVerCantante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busac-menu.png"))); // NOI18N
        itemMenuVerCantante.setMnemonic('s');
        itemMenuVerCantante.setText("Buscar cantante");
        itemMenuVerCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVerCantanteActionPerformed(evt);
            }
        });
        fileMenu.add(itemMenuVerCantante);

        menuItemActualizarCantante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar-menu.png"))); // NOI18N
        menuItemActualizarCantante.setMnemonic('a');
        menuItemActualizarCantante.setText("Actualizar cantante");
        menuItemActualizarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarCantanteActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemActualizarCantante);

        menuItemListarCantante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listar-menu.png"))); // NOI18N
        menuItemListarCantante.setText("Listar cantante");
        menuItemListarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarCantanteActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemListarCantante);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuDos-menu.png"))); // NOI18N
        jMenu1.setText("Disco");

        itemMenuRegistrarDisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listarDisco-menu.png"))); // NOI18N
        itemMenuRegistrarDisco.setText("Registrar disco");
        itemMenuRegistrarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRegistrarDiscoActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuRegistrarDisco);

        menuItemBuscarDisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dsicoBuscarmenu.png"))); // NOI18N
        menuItemBuscarDisco.setText("Buscar disco");
        menuItemBuscarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarDiscoActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemBuscarDisco);

        menuItemActualizarDisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disco-menu.png"))); // NOI18N
        menuItemActualizarDisco.setText("Actualizar disco");
        menuItemActualizarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarDiscoActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemActualizarDisco);

        menuItemEliminarDisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/discoElimnarMenu.png"))); // NOI18N
        menuItemEliminarDisco.setText("Eliminar disco");
        menuItemEliminarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarDiscoActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemEliminarDisco);

        menuItemListarDisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/discorafia-menu.png"))); // NOI18N
        menuItemListarDisco.setText("Listar disco");
        menuItemListarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarDiscoActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemListarDisco);

        fileMenu.add(jMenu1);

        menuBar.add(fileMenu);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuDos-menu.png"))); // NOI18N
        jMenu5.setText("Disco");

        itemMenuRegistrarDisco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listarDisco-menu.png"))); // NOI18N
        itemMenuRegistrarDisco2.setText("Registrar disco");
        itemMenuRegistrarDisco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRegistrarDisco2ActionPerformed(evt);
            }
        });
        jMenu5.add(itemMenuRegistrarDisco2);

        menuItemBuscarDisco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dsicoBuscarmenu.png"))); // NOI18N
        menuItemBuscarDisco2.setText("Buscar disco");
        menuItemBuscarDisco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarDisco2ActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemBuscarDisco2);

        menuItemActualizarDisco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disco-menu.png"))); // NOI18N
        menuItemActualizarDisco2.setText("Actualizar disco");
        menuItemActualizarDisco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarDisco2ActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemActualizarDisco2);

        menuItemEliminarDisco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/discoElimnarMenu.png"))); // NOI18N
        menuItemEliminarDisco2.setText("Eliminar disco");
        menuItemEliminarDisco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarDisco2ActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemEliminarDisco2);

        menuItemListarDisco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/discorafia-menu.png"))); // NOI18N
        menuItemListarDisco2.setText("Listar disco");
        menuItemListarDisco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarDisco2ActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemListarDisco2);

        menuBar.add(jMenu5);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuDos-menu.png"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Compositor");

        menuItemRegistrarCompositor.setMnemonic('t');
        menuItemRegistrarCompositor.setText("Registrar compositor");
        menuItemRegistrarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistrarCompositorActionPerformed(evt);
            }
        });
        editMenu.add(menuItemRegistrarCompositor);

        menuItemBuscarCompositor.setMnemonic('y');
        menuItemBuscarCompositor.setText("Buscar compositor");
        menuItemBuscarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarCompositorActionPerformed(evt);
            }
        });
        editMenu.add(menuItemBuscarCompositor);

        menuItemActualizarCompositor.setMnemonic('p');
        menuItemActualizarCompositor.setText("Actualizar compositor");
        menuItemActualizarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarCompositorActionPerformed(evt);
            }
        });
        editMenu.add(menuItemActualizarCompositor);

        menuItemEliminarCompositor.setMnemonic('d');
        menuItemEliminarCompositor.setText("Eliminar compositor");
        menuItemEliminarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarCompositorActionPerformed(evt);
            }
        });
        editMenu.add(menuItemEliminarCompositor);

        menuItemListarCompositor.setText("Listar compositores");
        menuItemListarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarCompositorActionPerformed(evt);
            }
        });
        editMenu.add(menuItemListarCompositor);

        jMenu2.setText("Cancion");

        menuItemRegistrarCancion.setText("Registrar cancion");
        menuItemRegistrarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistrarCancionActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemRegistrarCancion);

        menuItemBuscarCancion.setText("Buscar cancion");
        menuItemBuscarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarCancionActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemBuscarCancion);

        menuItemActualizarCancion.setText("Actualizar cancion");
        menuItemActualizarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarCancionActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemActualizarCancion);

        menuItemEliminarCancion.setText("Eliminar cancion");
        menuItemEliminarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarCancionActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemEliminarCancion);

        menuItemListarCancion.setText("Listar cancion");
        menuItemListarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarCancionActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemListarCancion);

        editMenu.add(jMenu2);

        jMenu6.setText("Cliente");

        menuItemRegistrarCliente.setText("Registar Cliente");
        menuItemRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistrarClienteActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemRegistrarCliente);

        menuItemBuscarCliente.setText("Buscar Cliente");
        menuItemBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarClienteActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemBuscarCliente);

        menuItemActulalizarCliente.setText("Actualizar Cliente");
        menuItemActulalizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActulalizarClienteActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemActulalizarCliente);

        editMenu.add(jMenu6);

        menuBar.add(editMenu);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuDos-menu.png"))); // NOI18N
        jMenu4.setText("Cancion");

        menuItemRegistrarCancion1.setText("Registrar cancion");
        menuItemRegistrarCancion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistrarCancion1ActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemRegistrarCancion1);

        menuItemBuscarCancion1.setText("Buscar cancion");
        menuItemBuscarCancion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarCancion1ActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemBuscarCancion1);

        menuItemActualizarCancion1.setText("Actualizar cancion");
        menuItemActualizarCancion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarCancion1ActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemActualizarCancion1);

        menuItemEliminarCancion1.setText("Eliminar cancion");
        menuItemEliminarCancion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarCancion1ActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemEliminarCancion1);

        menuItemListarCancion1.setText("Listar cancion");
        menuItemListarCancion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarCancion1ActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemListarCancion1);

        menuBar.add(jMenu4);

        menuItemRegistrarCliente1.setText("Cliente");

        menuItemRegistrarCliente2.setText("Registar Cliente");
        menuItemRegistrarCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistrarCliente2ActionPerformed(evt);
            }
        });
        menuItemRegistrarCliente1.add(menuItemRegistrarCliente2);

        menuItemBuscarCliente2.setText("Buscar Cliente");
        menuItemBuscarCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarCliente2ActionPerformed(evt);
            }
        });
        menuItemRegistrarCliente1.add(menuItemBuscarCliente2);

        menuItemActulalizarCliente1.setText("Actualizar Cliente");
        menuItemActulalizarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActulalizarCliente1ActionPerformed(evt);
            }
        });
        menuItemRegistrarCliente1.add(menuItemActulalizarCliente1);

        menuBar.add(menuItemRegistrarCliente1);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuCrearCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCrearCantanteActionPerformed
        if (ventanaCrearCantante == null) {
            ventanaCrearCantante = new VentanaCrearCantante(controladorCantante);
            desktopPane.add(ventanaCrearCantante);
        }
        ventanaCrearCantante.setVisible(true);
    }//GEN-LAST:event_itemMenuCrearCantanteActionPerformed

    private void itemMenuVerCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVerCantanteActionPerformed
        if (ventanaBuscarCantante == null) {
            ventanaBuscarCantante = new VentanaBuscarCantante(controladorCantante);
            desktopPane.add(ventanaBuscarCantante);
        }
        ventanaBuscarCantante.setVisible(true);
    }//GEN-LAST:event_itemMenuVerCantanteActionPerformed

    private void menuItemActualizarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarCantanteActionPerformed
         if (ventanaActualizarCantante == null) {
            ventanaActualizarCantante = new VentanaActualizarCantante(controladorCantante);
            desktopPane.add(ventanaActualizarCantante);
        }
        ventanaActualizarCantante.setVisible(true);
    }//GEN-LAST:event_menuItemActualizarCantanteActionPerformed

    private void menuItemListarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarCantanteActionPerformed
        if (ventanaListarCantante == null) {
            ventanaListarCantante = new VentanaListarCantante(controladorCantante);
            desktopPane.add(ventanaListarCantante);
        }
        ventanaListarCantante.setVisible(true);
    }//GEN-LAST:event_menuItemListarCantanteActionPerformed

    private void menuItemRegistrarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistrarCompositorActionPerformed
        if (ventanaCrearCompositor == null) {
            ventanaCrearCompositor = new VentanaCrearCompositor(controladorCompositor);
            desktopPane.add(ventanaCrearCompositor);
        }
        ventanaCrearCompositor.setVisible(true);
    }//GEN-LAST:event_menuItemRegistrarCompositorActionPerformed

    private void menuItemBuscarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarCompositorActionPerformed
        if (ventanaBuscarCompositor == null) {
            ventanaBuscarCompositor = new VentanaBuscarCompositor(controladorCompositor);
            desktopPane.add(ventanaBuscarCompositor);
        }
        ventanaBuscarCompositor.setVisible(true);
    }//GEN-LAST:event_menuItemBuscarCompositorActionPerformed

    private void menuItemActualizarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarCompositorActionPerformed
        if (ventanaActualizarCompositor == null) {
            ventanaActualizarCompositor = new VentanaActualizarCompositor(controladorCompositor);
            desktopPane.add(ventanaActualizarCompositor);
        }
        ventanaActualizarCompositor.setVisible(true);
    }//GEN-LAST:event_menuItemActualizarCompositorActionPerformed

    private void menuItemEliminarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarCompositorActionPerformed
        if (ventanaEliminarCompositor == null) {
            ventanaEliminarCompositor = new VentanaEliminarCompositor(controladorCompositor);
            desktopPane.add(ventanaEliminarCompositor);
        }
        ventanaEliminarCompositor.setVisible(true);
    }//GEN-LAST:event_menuItemEliminarCompositorActionPerformed

    private void menuItemListarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarCompositorActionPerformed
        if(ventanaListarCompositor==null){
            ventanaListarCompositor= new VentanaListarCompositor(controladorCompositor);
            desktopPane.add(ventanaListarCompositor);
        }
        ventanaListarCompositor.setVisible(true);
    }//GEN-LAST:event_menuItemListarCompositorActionPerformed

    private void itemMenuRegistrarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRegistrarDiscoActionPerformed
        if (ventanaCrearDisco == null) {
            ventanaCrearDisco = new VentanaCrearDisco(controladorCantante);
            desktopPane.add(ventanaCrearDisco);
        }
        ventanaCrearDisco.setVisible(true);
    }//GEN-LAST:event_itemMenuRegistrarDiscoActionPerformed

    private void menuItemBuscarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarDiscoActionPerformed
        if (ventanaBuscarDisco == null) {
            ventanaBuscarDisco= new VentanaBuscarDisco(controladorCantante);
            desktopPane.add(ventanaBuscarDisco);
        }
        ventanaBuscarDisco.setVisible(true);
    }//GEN-LAST:event_menuItemBuscarDiscoActionPerformed

    private void menuItemActualizarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarDiscoActionPerformed
        if (ventanaActualizarDisco == null) {
            ventanaActualizarDisco= new VentanaActualizarDisco(controladorCantante);
            desktopPane.add(ventanaActualizarDisco);
        }
        ventanaActualizarDisco.setVisible(true);
    }//GEN-LAST:event_menuItemActualizarDiscoActionPerformed

    private void menuItemEliminarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarDiscoActionPerformed
        if (ventanaEliminarDisco == null) {
            ventanaEliminarDisco= new VentanaEliminarDisco(controladorCantante);
            desktopPane.add(ventanaEliminarDisco);
        }
        ventanaEliminarDisco.setVisible(true);
    }//GEN-LAST:event_menuItemEliminarDiscoActionPerformed

    private void menuItemListarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarDiscoActionPerformed
        if (ventanaListarDisco == null) {
            ventanaListarDisco= new VentanaListarDisco(controladorCantante);
            desktopPane.add(ventanaListarDisco);
        }
        ventanaListarDisco.setVisible(true);
    }//GEN-LAST:event_menuItemListarDiscoActionPerformed

    private void menuItemRegistrarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistrarCancionActionPerformed
        if(ventanaCrearCancion==null){
            ventanaCrearCancion= new VentanaCrearCancion(controladorCompositor);
            desktopPane.add(ventanaCrearCancion);
        }
        ventanaCrearCancion.setVisible(true);
    }//GEN-LAST:event_menuItemRegistrarCancionActionPerformed

    private void menuItemBuscarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarCancionActionPerformed
        if(ventanaBuscarCancion==null){
            ventanaBuscarCancion= new VentanaBuscarCancion(controladorCompositor);
            desktopPane.add(ventanaBuscarCancion);
        }
        ventanaBuscarCancion.setVisible(true);
    }//GEN-LAST:event_menuItemBuscarCancionActionPerformed

    private void menuItemActualizarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarCancionActionPerformed
        if(ventanaActualizarCancion==null){
            ventanaActualizarCancion= new VentanaActualizarCancion(controladorCompositor);
            desktopPane.add(ventanaActualizarCancion);
        }
        ventanaActualizarCancion.setVisible(true);
    }//GEN-LAST:event_menuItemActualizarCancionActionPerformed

    private void menuItemEliminarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarCancionActionPerformed
        if(ventanaEliminarCancion==null){
            ventanaEliminarCancion= new VentanaEliminarCancion(controladorCompositor);
            desktopPane.add(ventanaEliminarCancion);
        }
        ventanaEliminarCancion.setVisible(true);
    }//GEN-LAST:event_menuItemEliminarCancionActionPerformed

    private void menuItemListarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarCancionActionPerformed
       if(ventanaListarCancion==null){
            ventanaListarCancion= new VentanaListarCancion(controladorCompositor);
            desktopPane.add(ventanaListarCancion);
        }
        ventanaListarCancion.setVisible(true);
    }//GEN-LAST:event_menuItemListarCancionActionPerformed

    private void menuItemRegistrarCancion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistrarCancion1ActionPerformed
        this.menuItemRegistrarCancionActionPerformed(evt);
    }//GEN-LAST:event_menuItemRegistrarCancion1ActionPerformed

    private void menuItemBuscarCancion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarCancion1ActionPerformed
        this.menuItemBuscarCancionActionPerformed(evt);
    }//GEN-LAST:event_menuItemBuscarCancion1ActionPerformed

    private void menuItemActualizarCancion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarCancion1ActionPerformed
        this.menuItemActualizarCancionActionPerformed(evt);
    }//GEN-LAST:event_menuItemActualizarCancion1ActionPerformed

    private void menuItemEliminarCancion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarCancion1ActionPerformed
        this.menuItemEliminarCancionActionPerformed(evt);
    }//GEN-LAST:event_menuItemEliminarCancion1ActionPerformed

    private void menuItemListarCancion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarCancion1ActionPerformed
        this.menuItemListarCancionActionPerformed(evt);
    }//GEN-LAST:event_menuItemListarCancion1ActionPerformed

    private void menuItemRegistrarCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistrarCliente2ActionPerformed
        this.menuItemRegistrarClienteActionPerformed(evt);
    }//GEN-LAST:event_menuItemRegistrarCliente2ActionPerformed

    private void menuItemRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistrarClienteActionPerformed
        if(ventanaCrearCliente ==null){
            ventanaCrearCliente= new VentanaCrearCliente(controladorCompositor, controladorCantante);
            desktopPane.add(ventanaCrearCliente);
        }
        ventanaCrearCliente.setVisible(true);
    }//GEN-LAST:event_menuItemRegistrarClienteActionPerformed

    private void menuItemBuscarCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarCliente2ActionPerformed
        this.menuItemBuscarClienteActionPerformed(evt);
    }//GEN-LAST:event_menuItemBuscarCliente2ActionPerformed

    private void menuItemBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarClienteActionPerformed
        if(ventanaBuscarCliente ==null){
            ventanaBuscarCliente= new VentanaBuscarCliente(controladorCompositor);
            desktopPane.add(ventanaBuscarCliente);
        }
        ventanaBuscarCliente.setVisible(true);
    }//GEN-LAST:event_menuItemBuscarClienteActionPerformed

    private void menuItemActulalizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActulalizarClienteActionPerformed
        if(ventanaActualizarCliente ==null){
            ventanaActualizarCliente= new VentanaActualizarCliente(controladorCompositor);
            desktopPane.add(ventanaActualizarCliente);
        }
        ventanaActualizarCliente.setVisible(true);
    }//GEN-LAST:event_menuItemActulalizarClienteActionPerformed

    private void menuItemActulalizarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActulalizarCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemActulalizarCliente1ActionPerformed

    private void itemMenuRegistrarDisco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRegistrarDisco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuRegistrarDisco2ActionPerformed

    private void menuItemBuscarDisco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarDisco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemBuscarDisco2ActionPerformed

    private void menuItemActualizarDisco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarDisco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemActualizarDisco2ActionPerformed

    private void menuItemEliminarDisco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarDisco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemEliminarDisco2ActionPerformed

    private void menuItemListarDisco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarDisco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemListarDisco2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem itemMenuCrearCantante;
    private javax.swing.JMenuItem itemMenuRegistrarDisco;
    private javax.swing.JMenuItem itemMenuRegistrarDisco2;
    private javax.swing.JMenuItem itemMenuVerCantante;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemActualizarCancion;
    private javax.swing.JMenuItem menuItemActualizarCancion1;
    private javax.swing.JMenuItem menuItemActualizarCantante;
    private javax.swing.JMenuItem menuItemActualizarCompositor;
    private javax.swing.JMenuItem menuItemActualizarDisco;
    private javax.swing.JMenuItem menuItemActualizarDisco2;
    private javax.swing.JMenuItem menuItemActulalizarCliente;
    private javax.swing.JMenuItem menuItemActulalizarCliente1;
    private javax.swing.JMenuItem menuItemBuscarCancion;
    private javax.swing.JMenuItem menuItemBuscarCancion1;
    private javax.swing.JMenuItem menuItemBuscarCliente;
    private javax.swing.JMenuItem menuItemBuscarCliente2;
    private javax.swing.JMenuItem menuItemBuscarCompositor;
    private javax.swing.JMenuItem menuItemBuscarDisco;
    private javax.swing.JMenuItem menuItemBuscarDisco2;
    private javax.swing.JMenuItem menuItemEliminarCancion;
    private javax.swing.JMenuItem menuItemEliminarCancion1;
    private javax.swing.JMenuItem menuItemEliminarCompositor;
    private javax.swing.JMenuItem menuItemEliminarDisco;
    private javax.swing.JMenuItem menuItemEliminarDisco2;
    private javax.swing.JMenuItem menuItemListarCancion;
    private javax.swing.JMenuItem menuItemListarCancion1;
    private javax.swing.JMenuItem menuItemListarCantante;
    private javax.swing.JMenuItem menuItemListarCompositor;
    private javax.swing.JMenuItem menuItemListarDisco;
    private javax.swing.JMenuItem menuItemListarDisco2;
    private javax.swing.JMenuItem menuItemRegistrarCancion;
    private javax.swing.JMenuItem menuItemRegistrarCancion1;
    private javax.swing.JMenuItem menuItemRegistrarCliente;
    private javax.swing.JMenu menuItemRegistrarCliente1;
    private javax.swing.JMenuItem menuItemRegistrarCliente2;
    private javax.swing.JMenuItem menuItemRegistrarCompositor;
    // End of variables declaration//GEN-END:variables

}
